# Usa una imagen de base de Maven para construir el proyecto
FROM maven:3.9.9-openjdk-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Usa una imagen de base de OpenJDK para ejecutar la aplicación
FROM openjdk:21-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]